# --- Base settings ---
spring.application.name=configuration-server
server.port=8012
# --- Loading config from GitHub ---
spring.cloud.config.server.git.uri=https://github.com/${GIT_USERNAME}/${GIT_REPO}
spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_TOKEN}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
# --- Actuator ---
management.endpoints.web.exposure.include=bus-refresh
# --- RabbitMQ ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_MQ_USERNAME}
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD}
# --- Spring Config Credentials ---
spring.security.user.name=${CONFIG_SERVER_USERNAME_ADMIN}
spring.security.user.password=${CONFIG_SERVER_PASSWORD_ADMIN}
spring.security.user.roles=ADMIN

my-spring.security.user.name=${CONFIG_SERVER_USERNAME_CLIENT}
my-spring.security.user.password=${CONFIG_SERVER_PASSWORD_CLIENT}
my-spring.security.user.roles=CLIENT