server.port=8081
#server.port=${PORT:0}
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance-id:${random.value}}

spring.devtools.restart.enabled=true

spring.application.name=users-api

# --- H2 Settings ---
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

spring.datasource.url=jdbc:h2:mem:test-bourbon-nook;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=REDACTED
spring.datasource.password=REDACTED
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect