server.port=8010
spring.application.name=discovery-service

# --- Eureka Server Settings ---
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka
# --- Security ---
#spring.security.user.name=${CONFIG_SERVER_USERNAME}
#spring.security.user.password=${CONFIG_SERVER_PASSWORD}
# --- Logging ---
logging.level.org.springframework.security=DEBUG
# --- Config Server ---
spring.config.import=configserver:http://localhost:8012
spring.cloud.config.username=${CONFIG_SERVER_USERNAME}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}