/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedBottlesIndexRouteImport } from './routes/_authenticated/bottles/index'
import { Route as AuthenticatedBottlesBottleIdRouteImport } from './routes/_authenticated/bottles/$bottleId'
import { Route as AuthenticatedBottlesNewRouteImport } from './routes/_authenticated/bottles/new'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedProfileChangePasswordRouteImport } from './routes/_authenticated/profile/change-password'
import { Route as AuthenticatedReviewsIndexRouteImport } from './routes/_authenticated/reviews/index'
import { Route as AuthenticatedReviewsReviewIdRouteImport } from './routes/_authenticated/reviews/$reviewId'
import { Route as AuthenticatedReviewsNewRouteImport } from './routes/_authenticated/reviews/new'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedBottlesBottleIdEditRouteImport } from './routes/_authenticated/bottles/$bottleId_.edit'
import { Route as AuthenticatedReviewsReviewIdEditRouteImport } from './routes/_authenticated/reviews/$reviewId_.edit'
import { Route as AuthenticatedAdminUsersUserIdEditRouteImport } from './routes/_authenticated/admin/users/$userId_.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBottlesIndexRoute =
  AuthenticatedBottlesIndexRouteImport.update({
    id: '/bottles/',
    path: '/bottles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBottlesBottleIdRoute =
  AuthenticatedBottlesBottleIdRouteImport.update({
    id: '/bottles/$bottleId',
    path: '/bottles/$bottleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBottlesNewRoute = AuthenticatedBottlesNewRouteImport.update({
  id: '/bottles/new',
  path: '/bottles/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileChangePasswordRoute =
  AuthenticatedProfileChangePasswordRouteImport.update({
    id: '/profile/change-password',
    path: '/profile/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReviewsIndexRoute =
  AuthenticatedReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReviewsReviewIdRoute =
  AuthenticatedReviewsReviewIdRouteImport.update({
    id: '/reviews/$reviewId',
    path: '/reviews/$reviewId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReviewsNewRoute = AuthenticatedReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBottlesBottleIdEditRoute =
  AuthenticatedBottlesBottleIdEditRouteImport.update({
    id: '/bottles/$bottleId_/edit',
    path: '/bottles/$bottleId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReviewsReviewIdEditRoute =
  AuthenticatedReviewsReviewIdEditRouteImport.update({
    id: '/reviews/$reviewId_/edit',
    path: '/reviews/$reviewId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersUserIdEditRoute =
  AuthenticatedAdminUsersUserIdEditRouteImport.update({
    id: '/users/$userId_/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/bottles/$bottleId': typeof AuthenticatedBottlesBottleIdRoute
  '/bottles/new': typeof AuthenticatedBottlesNewRoute
  '/profile/change-password': typeof AuthenticatedProfileChangePasswordRoute
  '/reviews/$reviewId': typeof AuthenticatedReviewsReviewIdRoute
  '/reviews/new': typeof AuthenticatedReviewsNewRoute
  '/bottles/': typeof AuthenticatedBottlesIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/bottles/$bottleId/edit': typeof AuthenticatedBottlesBottleIdEditRoute
  '/reviews/$reviewId/edit': typeof AuthenticatedReviewsReviewIdEditRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/users/$userId/edit': typeof AuthenticatedAdminUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/bottles/$bottleId': typeof AuthenticatedBottlesBottleIdRoute
  '/bottles/new': typeof AuthenticatedBottlesNewRoute
  '/profile/change-password': typeof AuthenticatedProfileChangePasswordRoute
  '/reviews/$reviewId': typeof AuthenticatedReviewsReviewIdRoute
  '/reviews/new': typeof AuthenticatedReviewsNewRoute
  '/bottles': typeof AuthenticatedBottlesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/reviews': typeof AuthenticatedReviewsIndexRoute
  '/bottles/$bottleId/edit': typeof AuthenticatedBottlesBottleIdEditRoute
  '/reviews/$reviewId/edit': typeof AuthenticatedReviewsReviewIdEditRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/users/$userId/edit': typeof AuthenticatedAdminUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/bottles/$bottleId': typeof AuthenticatedBottlesBottleIdRoute
  '/_authenticated/bottles/new': typeof AuthenticatedBottlesNewRoute
  '/_authenticated/profile/change-password': typeof AuthenticatedProfileChangePasswordRoute
  '/_authenticated/reviews/$reviewId': typeof AuthenticatedReviewsReviewIdRoute
  '/_authenticated/reviews/new': typeof AuthenticatedReviewsNewRoute
  '/_authenticated/bottles/': typeof AuthenticatedBottlesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/_authenticated/bottles/$bottleId_/edit': typeof AuthenticatedBottlesBottleIdEditRoute
  '/_authenticated/reviews/$reviewId_/edit': typeof AuthenticatedReviewsReviewIdEditRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin/users/$userId_/edit': typeof AuthenticatedAdminUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin'
    | '/admin/dashboard'
    | '/bottles/$bottleId'
    | '/bottles/new'
    | '/profile/change-password'
    | '/reviews/$reviewId'
    | '/reviews/new'
    | '/bottles/'
    | '/profile/'
    | '/reviews/'
    | '/bottles/$bottleId/edit'
    | '/reviews/$reviewId/edit'
    | '/admin/users/'
    | '/admin/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/admin'
    | '/'
    | '/admin/dashboard'
    | '/bottles/$bottleId'
    | '/bottles/new'
    | '/profile/change-password'
    | '/reviews/$reviewId'
    | '/reviews/new'
    | '/bottles'
    | '/profile'
    | '/reviews'
    | '/bottles/$bottleId/edit'
    | '/reviews/$reviewId/edit'
    | '/admin/users'
    | '/admin/users/$userId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/bottles/$bottleId'
    | '/_authenticated/bottles/new'
    | '/_authenticated/profile/change-password'
    | '/_authenticated/reviews/$reviewId'
    | '/_authenticated/reviews/new'
    | '/_authenticated/bottles/'
    | '/_authenticated/profile/'
    | '/_authenticated/reviews/'
    | '/_authenticated/bottles/$bottleId_/edit'
    | '/_authenticated/reviews/$reviewId_/edit'
    | '/_authenticated/admin/users/'
    | '/_authenticated/admin/users/$userId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/bottles/': {
      id: '/_authenticated/bottles/'
      path: '/bottles'
      fullPath: '/bottles/'
      preLoaderRoute: typeof AuthenticatedBottlesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bottles/$bottleId': {
      id: '/_authenticated/bottles/$bottleId'
      path: '/bottles/$bottleId'
      fullPath: '/bottles/$bottleId'
      preLoaderRoute: typeof AuthenticatedBottlesBottleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bottles/new': {
      id: '/_authenticated/bottles/new'
      path: '/bottles/new'
      fullPath: '/bottles/new'
      preLoaderRoute: typeof AuthenticatedBottlesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/change-password': {
      id: '/_authenticated/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof AuthenticatedProfileChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews/': {
      id: '/_authenticated/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthenticatedReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews/$reviewId': {
      id: '/_authenticated/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof AuthenticatedReviewsReviewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews/new': {
      id: '/_authenticated/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof AuthenticatedReviewsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/bottles/$bottleId_/edit': {
      id: '/_authenticated/bottles/$bottleId_/edit'
      path: '/bottles/$bottleId/edit'
      fullPath: '/bottles/$bottleId/edit'
      preLoaderRoute: typeof AuthenticatedBottlesBottleIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews/$reviewId_/edit': {
      id: '/_authenticated/reviews/$reviewId_/edit'
      path: '/reviews/$reviewId/edit'
      fullPath: '/reviews/$reviewId/edit'
      preLoaderRoute: typeof AuthenticatedReviewsReviewIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/$userId_/edit': {
      id: '/_authenticated/admin/users/$userId_/edit'
      path: '/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminUsersUserIdEditRoute: typeof AuthenticatedAdminUsersUserIdEditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  AuthenticatedAdminUsersUserIdEditRoute:
    AuthenticatedAdminUsersUserIdEditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBottlesBottleIdRoute: typeof AuthenticatedBottlesBottleIdRoute
  AuthenticatedBottlesNewRoute: typeof AuthenticatedBottlesNewRoute
  AuthenticatedProfileChangePasswordRoute: typeof AuthenticatedProfileChangePasswordRoute
  AuthenticatedReviewsReviewIdRoute: typeof AuthenticatedReviewsReviewIdRoute
  AuthenticatedReviewsNewRoute: typeof AuthenticatedReviewsNewRoute
  AuthenticatedBottlesIndexRoute: typeof AuthenticatedBottlesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedReviewsIndexRoute: typeof AuthenticatedReviewsIndexRoute
  AuthenticatedBottlesBottleIdEditRoute: typeof AuthenticatedBottlesBottleIdEditRoute
  AuthenticatedReviewsReviewIdEditRoute: typeof AuthenticatedReviewsReviewIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBottlesBottleIdRoute: AuthenticatedBottlesBottleIdRoute,
  AuthenticatedBottlesNewRoute: AuthenticatedBottlesNewRoute,
  AuthenticatedProfileChangePasswordRoute:
    AuthenticatedProfileChangePasswordRoute,
  AuthenticatedReviewsReviewIdRoute: AuthenticatedReviewsReviewIdRoute,
  AuthenticatedReviewsNewRoute: AuthenticatedReviewsNewRoute,
  AuthenticatedBottlesIndexRoute: AuthenticatedBottlesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedReviewsIndexRoute: AuthenticatedReviewsIndexRoute,
  AuthenticatedBottlesBottleIdEditRoute: AuthenticatedBottlesBottleIdEditRoute,
  AuthenticatedReviewsReviewIdEditRoute: AuthenticatedReviewsReviewIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
